print ('Hello World')
print ("Hello World")
print ("Jhon")
print ("Jhon Kennedy")
print ("Hi,I am Python")
print (25)
print (2*2)
print (2+5+9)
print ("Hello,","I","am","Jhon")
print ("Hello Jhon"+"How are you?")
print ("20" + "+" + "2" + "=" + "22")
print ("I am studing BS Bioinformatics")
print ("We are learning Object Oriented Programming from DR. Saqib Ali")